### ISSUE TITLE
Change layout of PC's stat pools

### ISSUE THREAD

**Issue by mrkwnzl** [mrkwnzl/cyphersystem-foundryvtt#135]
Continuation of #134.

@taylorsilva:

> I think this makes the relation between a pools current value and size more obvious.  I found when my friends and I were playing and making characters, that we constantly forgot about the "pool" value. I had to explain the relationship between the text boxes as "fractions".  I thought this might be a better way to visually show the two values. I noticed that the NPC sheet already displays health this way.
>
> After making that change it looked weird having Edge take up so much space so I shrunk it down to not be as large.
>
> **What do you think of these changes?**
>
> <img width="668" alt="image" src="https://user-images.githubusercontent.com/4583837/121817563-27ac8600-cc50-11eb-826f-0ed55ab28abf.png">

> Just noticed this project: https://github.com/mrkwnzl/cyphersystem-foundryvtt/projects/3
> What else did you have in mind? I wouldn't mind trying to tackle a few issues here and there.

@sharkbruhaha:

> I second this. And this is from people that have played at the table too, the positioning just throws them off for some reason.

**Comment by mrkwnzl** [comment]
I agree that this needs some love, but I’m not sure that this is it. But first, I’m a bit surprised that this caused some confusion with your players. The layout in the Foundry system is the same as it is on the official character sheet. Have your player been confused by that as well?

<img width="356" alt="Screen Shot 2021-06-15 at 09 31 49" src="https://user-images.githubusercontent.com/40534855/122011568-84c54a80-cdbc-11eb-8389-2761d7cf9311.png">

Challenges for a re-design (which I attempted when I moved the Tier, Effort, and XP values) are in my view:

1. It should save vertical space. Ideally, a redesign would allow for more space for the lower part of the character sheet. If it stays the same size, that’s also okay, but it must not be bigger.
2. It needs to work well with the optional fourth pool (which you seemed to have missed, @taylorsilva; at least there weren’t any changes for that in your PR, I believe). That is actually quite a big challenge, as that makes it hard to use horizontal space.
3. The most important stat, the current pool value, should be easily and quickly recognizable. That’s why I decided to go with the layout from the official character sheet. It makes clear what’s important there at the very first glance.
4. There needs to be enough space that the translations still fit. Some languages have ridiculously long words for he pools. In German, for example, “Speed” is “Geschwindigkeit.” A redesign must keep enough space for that, even when the optional fourth pool is enabled.

To be honest, I’m not sure that these changes meet that. Specifically, I think the empty space left and right of the edge is a bit inelegant (which is kind of ironic, as there isn’t really elegance in the first place, but I think I did an okay job using the space efficiently, which might in itself be a kind of elegance), but more importantly it seems to draw the attention because of the empty space around it. So the most important stat, the current value, is a bit lost.

I think the cost this pays is higher than the benefit of clarifying that the pool is the maximum value.

I’m very open to suggestions for that, but I found that to be really hard in my attempts. I fear that it needs bigger changes for the sheet as a whole to make it really satisfying, or at least a different solution for the fourth pool.

**Comment by mrkwnzl** [comment]
> Just noticed this project: https://github.com/mrkwnzl/cyphersystem-foundryvtt/projects/3
> What else did you have in mind? I wouldn't mind trying to tackle a few issues here and there.

Missed that part, sorry. I don’t have any specific ideas for that. I created the project because I wanted to work on that, but then the update for Foundry 0.8 came along, with some other features, so I haven’t really worked on that. Main point is that the sheets are kind of boring or bland and people seem to like their sheets to be a bit more atmospheric. Challenge here of course is that as a generic ruleset, we can’t just make it sci-fi or fantasy. Plus, as you might have guessed by now, I value practicability and function above style.

If you have any ideas, I’m all ears!

**Comment by taylorsilva** [comment]
Replicating my reply on discord over here.

Given your input, I'm going to keep the current layout of the sheet. I'm going to instead try and have the display of the first input box dynamically update to display a fraction of `currentValue / MaxPool`. I think this will make it easier for players to discover the relation between the two text boxes.

**Comment by mrkwnzl** [comment]
Just as a side note: I’ve written something up for contributing code, as I promised in the PR comment: [Contribution Guidelines](https://github.com/mrkwnzl/cyphersystem-foundryvtt/wiki/Contribution-Guidelines)

I think that’s mostly common practice, at least from my limited experience with smaller projects, so that’s probably nothing new to you. Most important thing, probably, is that you target the develop branch, when you have a PR.

**Comment by taylorsilva** [comment]
Would you be able to make the `develop` branch the default branch since it is the one you want PR's against? Not sure if this has any negative effects on installing the system in foundry.

Adding a `CONTRIBUTING.md` at the root of the repo is the most common practice I've seen. I find things get ignored in the wiki section of github. Having it in the root of the repo keeps it more front-and-center imo.

**Comment by mrkwnzl** [comment]
> Would you be able to make the `develop` branch the default branch since it is the one you want PR's against? Not sure if this has any negative effects on installing the system in foundry.

It wouldn’t necessarily have negative effects, but I think that the default branch should be stable in case someone wants to download the source code and use it directly (that is not by downloading it through the installer within Foundry). Some people seem to do that when they want to play around with the code without cloning it or when there are problems with the Foundry server.

Plus, I update the ReadMe occasionally in the develop branch and I’d like to show the release ReadMe in there. I believe that is more user-friendly.

But I’m not entirely sure that these are good reasons. You’d be the second person contributing, so I haven’t put much thought into it.

> Adding a `CONTRIBUTING.md` at the root of the repo is the most common practice I've seen. I find things get ignored in the wiki section of github. Having it in the root of the repo keeps it more front-and-center imo.

That’s a good idea. Will do that! Thanks!

**Comment by taylorsilva** [comment]
Alternative idea for branches then, make a PR template that mentions which branch PR's should target. Example: https://github.com/concourse/concourse/blob/master/.github/pull_request_template.md

**Comment by mrkwnzl** [comment]
Implemented in v1.18.0, including your suggestions for contribution. Thanks!
