### ISSUE TITLE
Actor with text fields is displayed wrongly when another Actor sheet is opened.

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#178]
**Describe the bug**  
An Actor sheet with text put in for Type, Descriptor and Focus has text visually replaced by journal links when another Actor is opened which has links in each of those three fields.

**Steps to reproduce the behavior**  
1. Open Actor sheet with text in the three fields.
2. Open Actor sheet with links in each of the three fields.
3. Observe that the fields in the first actor sheet visually show the links from the second sheet.
4. Close and re-open the first actor sheet
5. Observe that the fields show the original text again.

**Expected behavior**  
The text should remain in the Actor's fields.

**Screenshots**  

**Setup**  
 - Cypher System Version: 1.25.0
 - Foundry VTT Version: 0.,8.9
 - Native App/Browser: Chrome 94

**Additional context**

**Comment by mrkwnzl** [comment]
@NiceTSY Since you have created your own issue, I close this for now.
