### ISSUE TITLE
Opening a second Actor sheet duplicates the Trade Item buttons in the Equipment tab of the first Actor.

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#179]
**Describe the bug**  
See title.

**Steps to reproduce the behavior**  
1. Open an Actor sheet and select the Equipment tab
2. Open a second Actor sheet
3. Observe duplicate "Trace Item" buttons on the Equipment tab of the first Actor.

**Expected behavior**  
Actor sheets should not interfere with each other.

**Screenshots**  

**Setup**  
 - Cypher System Version: 1.25.0
 - Foundry VTT Version: 0.8.9
 - Native App/Browser: chrome 94

**Additional context**

**Comment by mrkwnzl** [comment]
Thanks for reporting!

@NiceTSY, I’ll keep these issues up here until they are resolved, in case there are questions.

**Comment by mrkwnzl** [comment]
@NiceTSY Since you have created your own issue, I close this for now.
