### ISSUE TITLE
Cypher does not work with Foundry VTT version 10

### ISSUE THREAD

**Issue by patrys** [mrkwnzl/cyphersystem-foundryvtt#253]
**Describe the bug**  
Foundry VTT version 10 (released today) once again changed the data structures so basic things like opening character sheets fail, and the console is full of deprecation warnings.

**Steps to reproduce the behavior**  
1. Install Foundry 9
2. Install Cypher
3. Create some characters
4. Upgrade to Foundry 10
5. Try to use the character sheets

**Expected behavior**  
It should work the same as it did before.

**Screenshots**  
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/81205/187781059-63656b57-069b-4632-879a-8d9ce93fbdde.png">

**Setup**  
 - Cypher System Version: 1.33.3
 - Foundry VTT Version: 10 Build 283
 - Native App/Browser: Safari

**Additional context**  
N/A

**Comment by mrkwnzl** [comment]
Will be fixed in Cypher system v2.0.0, coming sometime in September

**Comment by mrkwnzl** [comment]
Quick update: v2.0.0 is coming in October.
