### ISSUE TITLE
Links in Sentence Boxes

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#255]
**Describe the solution you'd like**  
Allow links to journal entries to be put into the Sentence boxes at the top of an Actor sheet so that it provides direct access for quickly opening up the full text of a Type/Descriptor/Focus/Other.

**Describe alternatives you've considered**  
- Adding links manually as a sentence into the "Notes" section of the Actor sheet, but it isn't as quick to access from there.
- The "Nice (TSY)" Add-Ons module provides this capability, but it would be nice for it to be core.

**Comment by mrkwnzl** [comment]
Closing this for now. If this is still relevant, feel free to re-open.
