### ISSUE TITLE
Add source field to each Item

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#256]
To support better linking to PDFs, add a source field to the Item definition.

Optionally, also provide a button next to the source field which will open that page in the PDF (this is already done in the Shadowrun 5e game system).   My pdf-pager module (https://github.com/farling42/fvtt-pdf-pager) provide `ui.pdfpager.openPDFByCode` which can do this from within the system code.

**Comment by mrkwnzl** [comment]
Can you elaborate on how that would look like? Where would that source field and the button be found? What would be the benefit compared to just drag the source into the description?

**Comment by mrkwnzl** [comment]
Closing this for now. If this is still relevant, feel free to re-open.
