### ISSUE TITLE
Controlling global GMI range in individual mode

### ISSUE THREAD

**Issue by mrkwnzl** [mrkwnzl/cyphersystem-foundryvtt#259]
@farling42 via https://discord.com/channels/836885417197436958/1001753635199389716/1032316769311932507

QUESTION: For the GM Intrusion range. I switched to individual, and used the "All player characters" to move all players up to 10, but when I switch back to Global GM intrusion the button is back at 1.

I think it would feel more logical if the "all player characters" button in the "individual" panel also kept the global setting at the same value - and vice-versa, switching from global to individual should keep the global value.
(This could just be my own preference, however)

**Comment by mrkwnzl** [comment]
I have one conceptual problem with that:

PC A has a range of 1–2, while PC B still has a range of 1. Something happens, so that the range increases by one for all players, so I use the controls for All Player Characters to increase the range to PC A 1–3 and PC B to 1–2. What’s the global GMI range now?

Right now, the global value is completely independent of individual values.

**Comment by farling42** [comment]
I don't have a strong opinion.
I suspect it also depends on what game mode you are using - e.g. Horror Mode would always use the global value.

**Comment by mrkwnzl** [comment]
I thought about this some more. I don’t think there’s a need to regularly switch between game modes and I think having them separate is conceptually easier to grasp (and to work with in macros and modules, as you don’t have to make a computation to infer the individual GMI range from the global one).
