### ISSUE TITLE
Add optional setting flag to lockStaticStatsMacro

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#266]
**Is your feature request related to a problem? Please describe.**  
The lockStaticStatsMacro simply toggles the state on the actor. In a loop I might want to set all actors to either locked or unlocked.

**Describe the solution you'd like**  
A simple additional parameter (like 'setting' in the example below) would be sufficient.

```js
export async function lockStaticStatsMacro(actor, setting) {
  // Check for PC actor
  if (!actor || actor.type != "pc") return  ui.notifications.warn(game.i18n.localize("CYPHERSYSTEM.MacroOnlyAppliesToPC"));

  actor.setFlag("cyphersystem", "disabledStaticStats", setting ?? !actor.getFlag("cyphersystem", "disabledStaticStats"));
}
```

**Comment by mrkwnzl** [comment]
If you are creating a macro for a loop anyway, why aren’t you setting the flag directly instead of going through the macro function?

**Comment by farling42** [comment]
Because from the macro user's point of view, I shouldn't need to know the specific name of the flag.

**Comment by mrkwnzl** [comment]
All right, done.
