### ISSUE TITLE
Remove "maximum" from the compatibility field.

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#280]
**Describe the bug**  
Unable to launch any worlds in Foundry 11 (prototype 1).

**Solution**
Remove the "maximum" field from the "compatibility" field.

The "maximum" field is only intended for use when a developer wants to definitely prevent a user trying to use a version of the system on a version of Foundry which is known to be incompatible.

**Comment by mrkwnzl** [comment]
How would I know if it will work in a future version? Convention seems to be to use the major release of Foundry as the maximum, while the verified release is used for the confirmed minor version.

I think it’s a good idea to restrict the maximum version until at least the beta so that people don’t update prematurely.

**Comment by farling42** [comment]
The verified version is to show guaranteed compatibility.
I'm just removing the maximum from all my modules, and will reinstate it if required on specific versions in the future.

**Comment by mrkwnzl** [comment]
Maybe I don’t understand what the difference between verified and maximum is, then. I didn’t find any clear documentation for that.

**Comment by farling42** [comment]
From https://foundryvtt.com/article/module-development/

**compatibility**: the compatibility field is an object key for capturing the sub-fields which defines the limits of your module's compatibility based on Foundry Virtual Tabletop version. It contains the following subfields:

- **minimum**: The module will not function for versions earlier than this.

- **verified**: The module has been verified to be compatible up to this version.

- **maximum**: The module will not function for newer versions than this.

**Comment by farling42** [comment]
The "will not function" cannot be certain until the newer version is released.

**Comment by mrkwnzl** [comment]
Ah, I overlooked that. Thanks!

The way I understand that is which minimum and maximum are the versions I support, while verified makes sure that I, as the developer, have tested that particular version.

So, having maximum version 10 in there seems to be the intended way. The system isn't supposed to be working on V11, yet. The haven't even looked at the changelog. It's a prototype version and users aren't supposed to use that, and I won't give support for that until way later in the development cycle, maybe even not before it's stable.

**Comment by farling42** [comment]
I was just looking at V11 for my modules, to see if they are affected by the initial changes to the underlying DB system.
