### ISSUE TITLE
Linked abilities, skills, and attacks

### ISSUE THREAD

**Issue by mrkwnzl** [mrkwnzl/cyphersystem-foundryvtt#282]
Function to create skills, abilities, and attacks right from the item sheets, which syncs its data with the linked items.

**Comment by farling42** [comment]
Would this be done by having the skills and combat items as children of the Ability Item? And they get transferred (active effect?) to the Actor when the Ability Item is added to the Actor? (And removed from the Actor when the ability Item is removed from the actor?)

The only extra logic would be handling stacking of skills - e.g. starting from Inability and then getting trained to Practised (or starting at Trained and upgrading to Specialized) - but only if the ability allows the skill change to be stacked.

**Comment by mrkwnzl** [comment]
I’m not sure, actually. I played around with that, I didn’t really like it. 

The idea was this: if you have Onslaught, you not only put that on your sheet as your ability, but also as an attack. That’s why the roll button on the abilities doesn’t roll, but only pays the points. You are supposed to use attacks or skills when you need to roll them (the alt-click is the concession because the roll dialog is also used to calculate different costs).

So, when I have a character that has Onslaught, I create an attack by hand. I thought it might be useful to create an attack from an ability with a click, but then I thought it would also be nice that, if I change one thing, such as the skill level, it gets changed in both the ability and the attack.

But then I implemented it, and I realized that Onslaught is actually two attacks, both with different damage. And many abilities that could be attacks have different values depending on the weapon, so I _regularly_ need multiple attacks per weapon and ability. So syncing is kind of useless anyway.

I'm now thinking that I just create a button with which an attack or skill could be duplicated with the current values set in the ability, just to make that step a little easier.

**Comment by mrkwnzl** [comment]
Done in v2.8.0
