### ISSUE TITLE
[French] Translation key or text missing ?

### ISSUE THREAD

**Issue by JhaelenTerear** [mrkwnzl/cyphersystem-foundryvtt#283]
**Describe the issue**  
When using the system in french, with the All-in-One Roll, when there is more than 1 level of facilitation (a skill and one level of effort by exemple), there is an "undefined" in place of the number of facilitation levels.

**Expected translation**  
I think it should be the number of facilitations in this location.

**Screenshots**  
![Capture d’écran 2023-01-30 230726](https://user-images.githubusercontent.com/58259514/215607977-d19ed35a-e13c-4214-be95-2dd0f0de8f0c.png)

**Setup**  
 - Cypher System Version: 2.3.0
 - Foundry VTT Version: 10.291
 - Native App/Browser: Edge, Chrome

**Comment by NiceTSY** [comment]
Thanks for the head's up I may have missed the transmation  strings for those. 
@mrkwnzl I will correct this tomorrow from the translation tool directly :)

**Comment by mrkwnzl** [comment]
The translations are a bit behind because the Weblate service we were using stopped working. I applied for the one from Foundry VTT Hub, but that has yet to be created. The person managing that had a busy time lately, so we’re going to have to wait a bit longer.

**Comment by JhaelenTerear** [comment]
Ok, no problem, it's not really a breaking bug 😛. Thanks for your answer !

**Comment by NiceTSY** [comment]
> The translations are a bit behind because the Weblate service we were using stopped working. I applied for the one from Foundry VTT Hub, but that has yet to be created. The person managing that had a busy time lately, so we’re going to have to wait a bit longer.

No wonder I was not able to access Weblate this morning. Let me know when and where I can fix this @mrkwnzl I will do it :)

**Comment by mrkwnzl** [comment]
Will do!

**Comment by mrkwnzl** [comment]
@JhaelenTerear Thanks for the proper bug report, by the way!

**Comment by NiceTSY** [comment]
This should be fixed in the next update from Weblate
