### ISSUE TITLE
Different versions of the character sheet do not sync

### ISSUE THREAD

**Issue by Svartsmurfen** [mrkwnzl/cyphersystem-foundryvtt#285]
**Describe the bug**  
Player Characters are located on the right menu, when appropriate submenu have been selected. From here, when you double-click a character icon you go to their respective character sheet. 
Character icons can also be placed on a map by dragging their icon to the map. 
When double-clicking character icons on the map and making changes to the sheet, the changes does not carry over to the character sheet you get to by double-clicking the character icon in the right menu. It seems like there are two versions of the same sheet that does not "talk" to each other.

**Steps to reproduce the behavior**  
1. Select “Actors” sub menu from the right side menu.
2. Drag an actor to the map.
3. Double-click the Actor on the map, change an item.
4. Double-click the same Actor on the menu on the right, observe that the previously changed item remains unchanged.

**Expected behavior**  
When making a change on an Actor, regardless of where, the change should carry over to other possible instances of that Actor. It’s like it have a local instance where it should be a global instance, so to speak.

**Screenshots**  
Non needed due to natural 20 on text description. 2 XP for me!

**Setup**  
 - Latest version of VTT, 10 build 291
-  Latest version of cypher system, 2.3.0
-  Tested on both local app (GM, me) and Edge browser (player), latest version.

**Additional context**  
I recall having this issue previously, before the VTT 10 migration, but never came around to report it. I’m pretty sure this have nothing to do with type of browser since other players have experienced the same issue with other browsers (Chrome and variations thereof). 
I hope this narrows it down somewhat.

**Comment by mrkwnzl** [comment]
Hey! This is due to the actor data link not being set in the prototype token (see https://foundryvtt.com/article/tokens/). Each token is then its own instance. This is desired for NPCs, but not PCs. There were different prototype defaults for PCs, but some update broke that. Version 2.2.1 of the Cypher system fixed that, but PCs created before that still have the Foundry default settings. you can change that in the prototype settings.

Does that fix your issue?

**Comment by Svartsmurfen** [comment]
Thanks for the speedy reply.
I fiddled around a bit and it indeed seem to fix the problem, unfortunately the linking seem to revert back to unlinked as soon as you replace the actor token. Also, it does not seem to survive map changes. It is entirely possible i changed the settings in the wrong place though. 

Since you said newly created actors don't have this problem, I just right clicked the affected actors and made a copy of them, renamed the old ones as backup and called it a day. So far in my testing they have all behaved as expected, so problem fixed.
I would suggest that copy/renaming would be a better fix for the issue should someone else have it, although I would never have thought about it if you hadn't explained the underlying system.

Thanks for the help, mate. Much appreciated!
2 XP for you! ;)

**Comment by mrkwnzl** [comment]
> Thanks for the speedy reply. I fiddled around a bit and it indeed seem to fix the problem, unfortunately the linking seem to revert back to unlinked as soon as you replace the actor token. Also, it does not seem to survive map changes. It is entirely possible i changed the settings in the wrong place though.

It sounds as if you changed the setting in the placed token, but you need to change it for the **prototype** token. See here: https://foundryvtt.com/article/tokens/

When placing new tokens, it takes it setting from the prototype token. If you change it there, it should then be working for newly placed tokens and on new scenes.

But I’m glad it worked out, either way.
