### ISSUE TITLE
Task failure

### ISSUE THREAD

**Issue by CaptainKalli** [mrkwnzl/cyphersystem-foundryvtt#296]
Hi,

If I give a base difficulty of 6 (18), the player is skilled and uses 2 efforts, why did the task fail on a 14? Below he also indicates that I would have managed a task rank 7?

![failure](https://user-images.githubusercontent.com/127958395/225319941-2dc348f9-36b3-411c-85fe-7d698e6c2e45.jpg)

**Comment by mrkwnzl** [comment]
This is a bug in the display of the effective difficulty, it should tell you that it's a success. Will be fixed in the next update.

Thanks for reporting!

**Comment by CaptainKalli** [comment]
hi,

ok thank you and thanks for the great work.

**Comment by mrkwnzl** [comment]
Fixed in v2.4.2

**Comment by CaptainKalli** [comment]
awesome <3
