### ISSUE TITLE
Propose Intrusion button should default to owner of currently selected token.

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#303]
If I have a token selected, it would be preferable if the "Propose Intrusion" button from the toolbar were to open with the owner of the currently selected token is set as the default player.

If the currently selected token doesn't have a player as an owner, then just display the list as is done currently (the first entry in the list seems to be the default value).

It would speed things up by not requiring the GM to open the drop-down menu, find the player name in the list, and select it.

**Comment by mrkwnzl** [comment]
Yeah, that makes sense. But I think at this point, we can skip the dialog completely and just propose the intrusion to the selected token, just like the macro does.

Will be in the next version.

**Comment by mrkwnzl** [comment]
Done in v2.6.0
