### ISSUE TITLE
Allow tags to modify stats just like recursions can

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#307]
It would be nice to have the stat modifiers that are present on the Recursion Items to also be on the Tag Items.

I'm just prepping a character for the Mastodon adventure for The Strange; and they are allowed to switch into a Battle Chrysalid form which is:
```
You can change and gain a battle chrysalid for up to one hour. In this new form, you add 4 points to your Might Pool, add 1 to your Might Edge, add 2 points to your Speed Pool, and add 1 to your Speed Edge.
```
It would be nice to have all these modifiers immediately applied/removed on selecting/deselecting the tag.

**Comment by mrkwnzl** [comment]
Already possible when marking a tag as exclusive. Or is there another use case I’m missing?

**Comment by mrkwnzl** [comment]
Sorry, I don't understand. Why isn't the tag marked as exclusive? If you want the Battle Chrysalid tag to change your stats, you can just mark it as exclusive. It just means that no other exclusive tag can be active at the same time, but all other tags still work as usual.

**Comment by farling42** [comment]
I was leaving exclusive to be when I have multiple tags from which I want to have only one selected.

I agree that enabling this tag as an "exclusive" tag provides the additional fields for me to edit - but it prevents me using the exclusive tag for something else which definitely does need to be exclusive. (I don't have a use case for this at the moment.)

**Comment by mrkwnzl** [comment]
I see. The intended use of exclusive tags is to change your stats, though, not to manage your active tags. If you are using them for equipment sets, for example, of which you usually only use one at a time, the intention is that you enable the one you want active and disable all other ones. I didn't mean to automate that.

**Comment by mrkwnzl** [comment]
Is this something that the active effects module can accomplish?

**Comment by farling42** [comment]
I think I have stat pool changes working now. But it would be nice for the core game system to treat all tags and recursions the same way.

**Comment by mrkwnzl** [comment]
Done in v2.11.0
