### ISSUE TITLE
Add hook for when tag or recursion is enabled or disabled

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#312]
In order for my active effects module to be able to manage effects on tags and recursions properly, it would be nice if the core cyphersystem generated a hook.callAll when the user enables or disables a specific recursion.

For mutually exclusive tags and recursions, it would be nice if the hook was called with "enabled=false" for the old selected tag/recursion (if any), and "enabled=true" for the newly selected tag/recursion (if any).

Example hooks:
```js
updateTag(actor, tagItem, enabled)
updateRecursion(actor, recursionItem, enabled)
```
or if it is best to avoid hook names that begin with "update" (since core Foundry can in theory do an update on any type of document):
```js
toggleTag(actor, tagItem, enabled)
toggleRecursion(actor, recursionItem, enabled)
```

**Comment by mrkwnzl** [comment]
Yes, I’ll do that, but I’ll have to refactor how recursions work first and integrate them into the tagging engine. Also, would two hooks per exclusive tag/recursion be useful? It’s at least easier for me to implement, as I only call one update for those.

```js
enableTab(actor, item);
disableTag(actor, item);
```

**Comment by farling42** [comment]
Two hooks would be fine.

Is the "item" parameter the tag item?

**Comment by farling42** [comment]
The `rollEngine` hook performs this correctly :-)

**Comment by mrkwnzl** [comment]
Wait, what? I don't even go through the roll engine when I toggle a tag or recursion, do I?
