### ISSUE TITLE
Recovery Roll appears in chat for the selected token rather than the correct Actor

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#318]
If I have a token selected, then the chat card for a recovery roll has the msg information for the selected token, rather than the character on which I pressed the recovery roll button. (I was logged in as GM when doing this.)

![image](https://github.com/mrkwnzl/cyphersystem-compendium/assets/17485384/bdf3bbae-3eb0-41a9-afb0-502bc09929fb)

All the msg information in this Chat Card should be for the actor on which I pressed the button and completely ignore any token which might be targeted.

(Note that on clicking the dice on Might, Speed or Intellect, the correct title is given in the Chat Card.)

This bug relates to an "Automated Animation" which is configured to play on the token of the character performing the recovery.

**Comment by mrkwnzl** [comment]
Fixed in the next update.
