### ISSUE TITLE
Leaving cost blank on combat/skill and rolling sets the pool to blank

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#336]
**Describe the bug**  
With a combat or skill with a skill chosen but nothing entered into the cost, using the skill blanks out the Actor's pool current value field.

**Expected behavior**  
The cost should be assumed to be 0, rather than using blank or NaN.

**Setup**  
 - Cypher System Version: 2.10.1
 - Foundry VTT Version: 10.309
 - Native App/Browser: Chrome 117.0.5938.92

**Additional context**  
In the all-in-one dialog, if you blank out the cost field, moving away from the field sets it to 0. This should probably happen in the Item editor too (but it would also need an extra check in the roll handling code to proper handle a blank cost).

**Comment by mrkwnzl** [comment]
Good catch! Will have a fix shortly.

**Comment by mrkwnzl** [comment]
Fixed in v2.10.2
