### ISSUE TITLE
Chat Portrait module breaks display of inline chat rolls

### ISSUE THREAD

**Issue by sebastianmarkow** [mrkwnzl/cyphersystem-foundryvtt#339]
**Describe the bug**  
As seen here: https://www.youtube.com/watch?v=fzGGAqi1zEw&t=6572s
Chat Portrait breaks display inline chat rolls.

https://github.com/p4535992/foundryvtt-chat-portrait

**Steps to reproduce the behavior**  
Activate Chat Portrait and roll

**Expected behavior**  
Inline rolls are full width of the chatbox.

**Screenshots**  
<a href="https://ibb.co/mXmKHSv"><img src="https://i.ibb.co/mXmKHSv/Screenshot-2023-10-02-at-11-52-27.png" alt="Screenshot-2023-10-02-at-11-52-27" border="0"></a>

**Setup**  
 - Cypher System Version: 2.10.2
 - Foundry VTT Version: 11.311
 - Chat Portrait Version: 0.9.1
 - Native App/Browser: Chrome

**Comment by mrkwnzl** [comment]
Thanks for reporting! It seems to be an issue with Chat Portrait, which I have reported and proposed a solution here: https://github.com/p4535992/foundryvtt-chat-portrait/issues/36

I’ll keep this open until we find a solution.

**Comment by mrkwnzl** [comment]
Found another, much simpler solution. Will have a fix in the next update.

**Comment by sebastianmarkow** [comment]
Hey thanks @mrkwnzl for the fast fix.

**Comment by mrkwnzl** [comment]
Fixed in v2.10.3
