### ISSUE TITLE
Use of Token Tooltip Alt

### ISSUE THREAD

**Issue by AgostinhoMestre** [mrkwnzl/cyphersystem-foundryvtt#34]
Whath the parameters for the attributes to insert in tolltip manager?

**Comment by sharkbruhaha** [comment]
This is not a bug, don't report as such. Also, you'd get easier reply on the FoundryVTT system discord room.

The values are:
pools.might.value 
pools.intellect.value
pools.speed.value

**Comment by mrkwnzl** [comment]
Thanks for answering, @sharkbruhaha. I have created a question template for cases like this.

@AgostinhoMestre, has this worked for you? Feel free to re-open this issue if you have further questions about this. Or simply write me over on Discord.
