### ISSUE TITLE
Error reported when opening an Item from a locked compendium

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#342]
The extra code in CypherItemSheet.getData which calls this.item.update() needs some extra protection - the extra work should not be done if `data.editable` is false (data being the value returned by super.getData() at the start of the function).

This was first noticed when the GM is opening an Item in a compendium which was locked.

**Comment by mrkwnzl** [comment]
Good catch! Fixed in the next update.
