### ISSUE TITLE
Character Sheet is Not Scrollable

### ISSUE THREAD

**Issue by revwez** [mrkwnzl/cyphersystem-foundryvtt#344]
**Describe the bug**  
I am on a Mac running Foundry v11 and this system (everything is on the latest version).

The Character Sheet cannot scroll vertically. So in the settings dialog, for example, I have no way of accessing any of the dialogs below "sort skills by rating."

**Steps to reproduce the behavior**  
1. Open a sheet
2. Click on the settings tab
3. See the error

**Expected behavior**  
Previously I was able to scroll down through these options.

**Screenshots**  
Attached
![Screenshot 2023-10-28 at 9 09 36 PM](https://github.com/mrkwnzl/cyphersystem-foundryvtt/assets/100106394/1b46790e-5b45-4b9a-b7e3-134f9cd1375b)

**Setup**  
 - Cypher System Version: 2.10.3
 - Foundry VTT Version: v11.313
 - Native App/Browser: Tested Brave, Firefox, Safari

**Additional context**

**Comment by revwez** [comment]
Close this, it's a custom sheet issue (I should have checked). I'll report the bug over there.

**Comment by mrkwnzl** [comment]
Thank you for reporting anyway! I’ll keep this as a known but open for a while, in case someone else checks here.
