### ISSUE TITLE
Tag editor's sorting popup is not populated with custom names.

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#346]
When new names have been entered in the Tag Categories section of the Actor sheet, creating/editing a Tag does not populate the Sorting dropdown menu with the available tag categories.

**Comment by mrkwnzl** [comment]
Not a bug. The other category sortings work the same. You need to enter a name for a category so that it appears in that list. The reason is that if you need only two categories, you don’t want to have two useless “Tags 3” and “Tags 4” categories in that list.

**Comment by farling42** [comment]
I did enter a name, as well as changing the name in the first box.
The entries don't appear in the sorted list.
![image](https://github.com/mrkwnzl/cyphersystem-foundryvtt/assets/17485384/4d131b5a-0897-40cd-95b9-a044293ded61)

![image](https://github.com/mrkwnzl/cyphersystem-foundryvtt/assets/17485384/a6accde4-5c4d-4430-9e56-c09ec8ecdf09)

**Comment by mrkwnzl** [comment]
That’s a bug, then. Fix coming in a minute.
