### ISSUE TITLE
Actors/PC to have an additional "pool" for combined health

### ISSUE THREAD

**Issue by Wemo99** [mrkwnzl/cyphersystem-foundryvtt#349]
To provide an overview of the health of a token regardless of a actor/pc or npc, calculate the overall health that can be added to other modules or tokens.

This value does not need to be shown anywhere, just held behind the scenes for macros and other modules.

For the PC add an additional node to co-exist along side the other pools:
      "pools": {
        "health": {
          "value": 3,
          "max": 3
        }

These being equal to:
value = @pools.might.value + @pools.speed.value + @pools.intellect.value
max = @pools.might.max+ @pools.speed.max + @pools.intellect.max

As one of the traditional pools are modified, this new "health" pool is also adjusted.

**Comment by mrkwnzl** [comment]
Thanks for your suggestion.

Do you have a specific use case for that? The rules don’t operate with such a health value as far as I can tell, and for macros you can just add them together with two lines as you did there. So I’m not quite sure in what to do with that.

**Comment by mrkwnzl** [comment]
I’m closing this for now as part of the regular house keeping. Feel free to re-open this issue if you want to give additional information. I’m not opposed to doing that if there’s a good use case.
