### ISSUE TITLE
copy-as-armor doesn't work anymore

### ISSUE THREAD

**Issue by Rudi6691** [mrkwnzl/cyphersystem-foundryvtt#351]
**Describe the bug**  
Abilities can be copied as skills, and attacks, but not anymore as armor on their settings page.

**Steps to reproduce the behavior**  
1. Go to any ability of an actor, and open its item sheet.
2. Click on 'Settings'
3. Scroll down to 'Copy as ...'
4. Click on 'Armor'.

**Expected behavior**  
Message shown, that says that the ability was copied as an armor, but instead nothing happens.

**Screenshots**  
Not applicable, as nothing happens.

**Setup**  
 - Cypher System Version: 2.12.0
 - Foundry VTT Version: V11 Build 315
 - Native App/Browser: Chrome

**Additional context**  
Works for skills and attacks.

**Comment by mrkwnzl** [comment]
Good catch, thanks! Will be fixed in the next update!

**Comment by Rudi6691** [comment]
Great!
Guten Rutsch! :)
