### ISSUE TITLE
Add more information to chat log file

### ISSUE THREAD

**Issue by farling42** [mrkwnzl/cyphersystem-foundryvtt#359]
**Is your feature request related to a problem? Please describe.**  
Add more of the chat card text into the card log file.

**Describe the solution you'd like**  

**Describe alternatives you've considered**  

**Setup**  
Cypher System Version: 2.13.1
Foundry VTT Version: 11.315
Native App/Browser: Chrome Version 121.0.6167.86 (Official Build) (64-bit)

**Additional context**  
Core Foundry only puts the dice roll and formula into the log file.
The additional text that is displayed in Foundry's chat card is completely missing, so there is no context to the dice roll added to the chat log file.

For the following chat card:
![image](https://github.com/mrkwnzl/cyphersystem-foundryvtt/assets/17485384/ed492e28-c0d9-4a5b-9358-176ab5eac489)

The chat log file contains only:

```
[1/30/2024, 10:43:07 PM] Rory Alexander (Kazron)
8
1d6 + 3 = 5 + 3 = 8
```

**Comment by farling42** [comment]
`ChatMessage#export` needs to be overridden to provide more text in the output.

(possibly just setting `ChatMessage.content` to the correct HTML for the other text might be enough.

**Comment by mrkwnzl** [comment]
Can you elaborate on what problem this solves?

**Comment by mrkwnzl** [comment]
This also seems like a core Foundry issue. The label text really should be part of the log, regardless of where the roll comes from. If I do it in the Cypher system, this won't work for roll made with macros, in the chat directly, or using another module.

**Comment by farling42** [comment]
> Can you elaborate on what problem this solves?

As shown in the images above, the flavor text isn't appearing in the log file, so I have no idea what the logged dice roll was for.

I agree that the flavor field isn't being put into the log by core Foundry, but if core did do this then core might still not pick up the nested information inside the flavor box.

**Comment by farling42** [comment]
Actually, it looks like a feature/bug in core Foundry.

Roll.toMessage() isn't putting the flavor text into the chatlog.content, so it won't be put into the log file.

**Comment by mrkwnzl** [comment]
> As shown in the images above, the flavor text isn't appearing in the log file, so I have no idea what the logged dice roll was for.

I got that part. What are you using the logs for?

**Comment by farling42** [comment]
> > As shown in the images above, the flavor text isn't appearing in the log file, so I have no idea what the logged dice roll was for.
> 
> I got that part. What are you using the logs for?

As a backup to know what happened over the campaign, rather than never clearing out the in-game chat log.

**Comment by farling42** [comment]
I'm happy to close this issue, as it is a problem with core Foundry
