### ISSUE TITLE
New "type" is not recognized by the system

### ISSUE THREAD

**Issue by paulyhedral** [mrkwnzl/cyphersystem-foundryvtt#360]
**Describe the bug**  
New "type" is not recognized by the system

**Steps to reproduce the behavior**  
1. Go to Compendium Packs
2. Create Journal Compendium called "Types: Destiny"
3. In Compendium view, click "Create Journal Entry" and name it "Delve"
4. Click "Add Page", select type "Text", and name it "Delve"
5. Click edit icon in upper-right corner
6. Enter Delve contents, particularly "@type" as the initial text, and other content
7. Also make sure to add "@ability <some ability> @tier 1"
8. Save
9. Create new Actor
10. Drag "Delve" entry from Compendium view onto Actor sheet
11. See nothing happen

**Expected behavior**  
The Actor's "type" field should have the "Delve" entry show up, be clickable, and the "Abilities" tab should include the ability that was added to the type.

**Setup**  
 - Cypher System Version: v2.13.1
 - Foundry VTT Version: v11.315
 - Native App/Browser: Unite Browser 5.1.4 or Google Chrome 123.0.6312.59 on Mac
 - Hosted on Forge

**Additional context**  
I basically copied the format of Type entries from the Cypher System Compendium so that I could add the types in Numenera Destiny.

**Comment by mrkwnzl** [comment]
This isn’t a feature of the Cypher system. Please refer this to the module. I think this is from https://github.com/NiceTSY/nice-cypher-add-ons

**Comment by paulyhedral** [comment]
Ah, thanks. I will open an issue there. https://github.com/NiceTSY/nice-cypher-add-ons/issues/35
