### ISSUE TITLE
[Feature Request] Increment existing Items when a copy is dragged onto the sheet, instead of creating new

### ISSUE THREAD

**Issue by sharkbruhaha** [mrkwnzl/cyphersystem-foundryvtt#38]
Currently when you drag and drop an item from the chat log (result of a rollTable) it adds a new instance of the item instead of incrementing the existing entry. Is it possible to change this functionality?

**Comment by mrkwnzl** [comment]
Can’t make any promises, but I’ll look into it.

**Comment by mrkwnzl** [comment]
Design questions about this.

1. I thought it might be desirable to not only increase the quantity by one when dropping items, but by the quantity of the dragged item. That means that if you drag & drop an item with a quantity of 0 or null, nothing happens. Does that make sense?
2. Some items that do not have a quantity value (such as skills, cyphers, abilities). Should those items always be duplicated or should instead nothing happen?
