### ISSUE TITLE
[Feature Request] Renameable Inventory Categories

### ISSUE THREAD

**Issue by MithralDream** [mrkwnzl/cyphersystem-foundryvtt#51]
The names for the Materials and Currency sections on the character sheet can be modified, and the same function would be neat for Cyphers, Artifacts and Oddities, since some games might call them different names, i.e Mementos in Unmasked or Ephemera in Invisible Sun.

**Comment by mrkwnzl** [comment]
Thanks for the suggestion! Will be in the next version.
