### ISSUE TITLE
[Bug] Default image not showing due to broken link on linux system

### ISSUE THREAD

**Issue by NiceTSY** [mrkwnzl/cyphersystem-foundryvtt#63]
**Describe the bug**  
The default image for most of the actor's sheets does not show due to a broken link (mostly due to how Linux see path).
Not really a big issue, but a bit annoying.

**Steps to reproduce the behaviour**  
1. Create any kind of actor

**Expected behaviour**  
To see the correct image.

**Screenshots**  
![image](https://user-images.githubusercontent.com/38940602/108204302-ea157180-7123-11eb-9ea0-fde77b1388f8.png)
![image](https://user-images.githubusercontent.com/38940602/108204432-17fab600-7124-11eb-8be0-74136a5065d7.png)

Same for NPC, Companion, Community, etc.

**Setup**  
 - Cypher System Version: 1.13.0
 - Foundry VTT Version: 0.7.9
 - Native App/Browser: All
 - Hosting System: Linux

**Additional context**  
Solution: renaming the files to non-capital letters or trying to get them with a capital letter

**Comment by mrkwnzl** [comment]
Forgot about linux again. Sorry about that. Will be fixed shortly. Thanks for reporting.

**Comment by NiceTSY** [comment]
No worries, I made it for you if you want :)

**Comment by mrkwnzl** [comment]
Thanks for doing that! I need to adjust some other things, but I’ll publish 1.13.2 shortly.
