### ISSUE TITLE
[Bug] Edge not subtracted from cost of quick rolls

### ISSUE THREAD

**Issue by cityofkeats** [mrkwnzl/cyphersystem-foundryvtt#65]
**Describe the bug**  
Edge works properly on All-in-One Rolls, but not for Quick Rolls (All-in-One Template or Dragged to Bar).

**Steps to reproduce the behavior** 
For dragged ability
1. Go to a character sheet -> Abilities
2. Create a new ability with a positive cost.
3. Set the character's Edge for the corresponding pool to a positive value.
4. Drag ability to macro bar to create a macro.
5. Execute the macro.
6. The ability's corresponding pool will decrease by the value set in the ability, disregarding Edge.

For AiO Template
1. Using the Quick Roll (All-in-One Template), change the cost to a positive value.
2. Set the character's Edge for the corresponding pool to a positive value.
3. Execute the macro.
4. The ability's corresponding pool will decrease by the value set in the macro, disregarding Edge.

**Expected behavior**  
Edge should be subtracted from the cost of an ability before subtracting from the pool.

**Setup**  
 - Cypher System Version: 1.13.4
 - Foundry VTT Version: 0.7.9
 - Native App/Browser: Chrome

**Additional context**  
I am testing this as a GM controlling a player token in the standalone application.

**Comment by mrkwnzl** [comment]
Confirmed. Will be fixed in the next update.
