### ISSUE TITLE
[Bug] Edge are not computed in Abilities and in Effort for the All-in-Roll template

### ISSUE THREAD

**Issue by NiceTSY** [mrkwnzl/cyphersystem-foundryvtt#67]
**Describe the bug**  
Edges are not compted in the All-in-Roll template macro.

**Steps to reproduce the behaviour**  
1. Take any abilities
2. Put it inside the macro bar
3. Launch the ability
4. It will cost you the whole thing without taking into account the Edge

**Expected behaviour**  
To count the Edge rightfully ^^

**Screenshots**  
None

**Setup**  
 - Cypher System Version: 1.13.6
 - Foundry VTT Version: 0.7.9
 - Native App/Browser: All

**Comment by mrkwnzl** [comment]
I’m a bit confused. You say it doesn’t work with the All-in-One-Roll template macro, but tell me to use a different macro (the one generated when dragging an ability). Both seem to work correctly on my end. Can you elaborate?

**Comment by mrkwnzl** [comment]
I think I found what you were experiencing. I calculated the wrong Edge and didn’t notice. A fix will be on the way later today.

**Comment by mrkwnzl** [comment]
v1.13.7 hopefully fixes this. Can you confirm that it’s working now?

**Comment by NiceTSY** [comment]
Sorry if my wording was confusing. I was speaking about the All-in-One Dialog option (second option in the settings).
Now the Edge are properly computed well done!!! And many thanks as always for your work! :D

**Comment by mrkwnzl** [comment]
Thanks! Sorry for the inconvenience!
