### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by mrkwnzl** [mrkwnzl/cyphersystem-foundryvtt#71]

**Comment by Kadomi** [comment]
Reporting in for translation assistance. :-)

**Comment by smaug18** [comment]
Let me know how I can help.

**Comment by mrkwnzl** [comment]
We’re getting access to Weblate, a collaborative web tool for translations, from the awesome people who did the Spanish translation. I’ll share the link as soon as everything is set up. When the German translation is done and tested, I’ll publish v1.14.0 with all the translations included.

**Comment by mrkwnzl** [comment]
All right, everything is set up now. You can work on the translation here: [https://trans.etranslator.eu/projects/foundry-cypher-system/system/de/]()

The “Translate” button should send you to the translation interface where you can go through the strings one by one. Since I just copy & pasted the English file, the English text is in the translated field. Just replace that with the German ones. For testing purposes, I translated a few strings already, but feel free to revise that. For example, I’m not sure how “Items” (the Foundry class) is translated, so if you have more insight, just revise away.

Thank you so much for working on that! Let me know if you have questions.

**Comment by Kadomi** [comment]
Is there any way to make a note in Weblate? I am almost done with my initial pass, but wanted to mention that Practiced and Trained have both been translated to Geübt in the official German translation of Numenera.

**Comment by mrkwnzl** [comment]
There is a comment button below the translation field, which can be used for something like that.

Has there been a translation of Discovery and Destiny? “Practiced” should be the skill rating, which, as far as I know, wasn’t there in the old core rulebook.

**Comment by Kadomi** [comment]
No, there is no translation for Discovery and Destiny. Doubt there will be one, to be honest. Same with the Cypher System Rulebook or any of the campaign worlds, too much of a niche market for German publishers. 

In any case, I am done with the initial translation, and left a few comments.

**Comment by mrkwnzl** [comment]
> No, there is no translation for Discovery and Destiny. Doubt there will be one, to be honest. Same with the Cypher System Rulebook or any of the campaign worlds, too much of a niche market for German publishers.

Would “Ungeübt” be a viable translation for “Practiced” in the context of skill ratings?

> In any case, I am done with the initial translation, and left a few comments.

That was quick! Awesome! Thank you so much! @smaug18 Would you like to make a pass as well and take a look, especially to translations with comments?

**Comment by smaug18** [comment]
Yes, I will take a look today. I do not have the German books available but I am a native speaker and can do a second pass here. I'll check the comments too.

About trained/practiced, that's iffy. As I understand it the official translation for trained is "geübt", so we should keep that. For practiced I could see "ungeübt" or maybe "erfahren"?

**Comment by Kadomi** [comment]
> Would “Ungeübt” be a viable translation for “Practiced” in the context of skill ratings?

Ungeübt means 'untrained' so that wouldn't work. I could see 'erfahren' as @smaug18 suggested below. The literal translation for that is 'experienced'.
 
> That was quick! Awesome! Thank you so much!

I am off work this week, so I had the time. :-)

**Comment by mrkwnzl** [comment]
“Erfahren” sounds better than “geübt” to me, so that might be confusing. 

A completely different approach would be to not translate it and just put a “—” in there.

**Comment by smaug18** [comment]
I know what you mean but practiced and trained is also not that clearly differenciated imho.

**Comment by smaug18** [comment]
I went through the list first of all very well done @Kadomi. I made proposals only, did not directly change anything.

**Comment by mrkwnzl** [comment]
> I know what you mean but practiced and trained is also not that clearly differenciated imho.

That is true. The problem is that “trained” has been translated as “geübt“, where “ausgebildet” or “geschult” would be more accurate. “Trained” has the connotation of *formal* training that “practiced” lacks. It’s hard to transport that when “geübt” ist the one that should have the connotation of formal training.

**Comment by mrkwnzl** [comment]
> I went through the list first of all very well done @Kadomi. I made proposals only, did not directly change anything.

Some of the suggestions were about items. The Foundry class items (the other important one is actors) aren’t translated in the German translation of Foundry (i.e. they are called “Items”). I think it would be good practice to follow that translation. Are there instances where we really need “Gegenstände?”

**Comment by Kadomi** [comment]
> > I went through the list first of all very well done @Kadomi. I made proposals only, did not directly change anything.
> 
> Some of the suggestions were about items. The Foundry class items (the other important one is actors) aren’t translated in the German translation of Foundry (i.e. they are called “Items”). I think it would be good practice to follow that translation. Are there instances where we really need “Gegenstände?”

I should have double-checked that. I thought you were referring to equipment items where I said 'Gegenstände' and left it as items where it was obvious that you were referring to the Foundry class items. I concur, it should be Item/s whereever it is referring to the Foundry class items.

**Comment by smaug18** [comment]
> That is true. The problem is that “trained” has been translated as “geübt“, where “ausgebildet” or “geschult” would be more accurate. “Trained” has the connotation of _formal_ training that “practiced” lacks. It’s hard to transport that when “geübt” ist the one that should have the connotation of formal training.

Yes, that's the existing translation is the root of the problem. I like your idea of just using "-" for this reason.

**Comment by smaug18** [comment]
> Some of the suggestions were about items. The Foundry class items (the other important one is actors) aren’t translated in the German translation of Foundry (i.e. they are called “Items”). I think it would be good practice to follow that translation. Are there instances where we really need “Gegenstände?”

I wasn't aware of that and was thinking about a general inventory related term. I think there were instances of using "Gegenstände" before I sent my proposals.

**Comment by smaug18** [comment]
I thought about the "Power Shifts". Since this is a game term where there is no official translation available, I would opt to keep it untranslated. It might be difficult for the user to link this to the sourcebooks otherwise. Of course this is a general issue when only a few thing have official translations but this a very Cypher System specific term I feel.

**Comment by Kadomi** [comment]
> I thought about the "Power Shifts". Since this is a game term where there is no official translation available, I would opt to keep it untranslated. It might be difficult for the user to link this to the sourcebooks otherwise. Of course this is a general issue when only a few thing have official translations but this a very Cypher System specific term I feel.

That sounds sensible to me. I feel it's comparable to Edge or Pool, it's much better left alone, and would still make sense.

**Comment by mrkwnzl** [comment]
I'm going ahead and close this issue for now. For specific discussions of the translation, it's better to open a new one.
