### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by mrkwnzl** [mrkwnzl/cyphersystem-foundryvtt#74]

**Comment by NiceTSY** [comment]
If I am not mistaking, I already included the French translation in my PR :)

**Comment by mrkwnzl** [comment]
Yeah, I was hoping you could take a look again, as I had to change some things. Make sure that everything still is there where it should be. Plus, macro and system setting translations are coming up, and I was hoping you could help out there as well.

Sorry, I haven’t put a description here, yet.

**Comment by NiceTSY** [comment]
No worries, my bad for going through the whole thing too fast.
Settings were my next own assignment with the macro, so I will probably look at them this week.

Will have a look if everything behaves normally. 
Moreover, I will probably start on the Spanish translation soon too ;)

**Comment by mrkwnzl** [comment]
Quick heads up: I added Actor and Item strings to the English source file, so that the terms are translated as well. Those need translations as well.

**Comment by mrkwnzl** [comment]
Quick heads up: I added Actor and Item strings to the English source file, so that the terms are translated as well. Those need translations as well.

**Comment by NiceTSY** [comment]
Updated on the Weblate platform :)

**Comment by mrkwnzl** [comment]
I'm going ahead and close this issue for now. For specific discussions of the translation, it's better to open a new one.
