### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by mrkwnzl** [mrkwnzl/cyphersystem-foundryvtt#75]

**Comment by parvusdomus** [comment]
Hello mrkwnzl, yep, I was not being notified because I had configured the repo to the translation branch and this one no longer exist (it is the develop branch now), I changed it and now it updated and showed the untranslated, part. I'll have a look at this and do the pr when ready.

**Comment by mrkwnzl** [comment]
Awesome! Thanks! Since the French and German translations also come along, I thought it would be best to bring all up to speed on the develop branch. Would it be possible that the other languages also use Weblate?

**Comment by parvusdomus** [comment]
Not, that I am aware of, in the server I use we only have the spanish translation. No one opened translations for other languages there.

**Comment by mrkwnzl** [comment]
Do you think it would be possible to add other languages? Or is the Weblate instance used exclusively for Spanish translations?

**Comment by parvusdomus** [comment]
The server is not mine, and as far as I know it is used for spanish, galician, vasque... for several systems and modules, not sure if the owner will agree but I can ask him.

**Comment by mrkwnzl** [comment]
That would be awesome! Thanks!

**Comment by parvusdomus** [comment]
#88

**Comment by mrkwnzl** [comment]
All right, that was quick! Thanks a lot! When the German translation is done, I’ll publish a new version with all the translations included.

**Comment by mrkwnzl** [comment]
Quick heads up: I added Actor and Item strings to the English source file, so that the terms are translated as well. Those need translations as well.

**Comment by parvusdomus** [comment]
Done (not sure if I did the pr properly, please let me know if it is ok).

**Comment by mrkwnzl** [comment]
Looking good! Thanks a lot!
