### ISSUE TITLE
Translation of Plural of Power Shifts

### ISSUE THREAD

**Issue by mrkwnzl** [mrkwnzl/cyphersystem-foundryvtt#84]
This one is tricky. That only works for languages which have a plural -s, where the word stem stays the same. All other languages need a different solution.

_Originally posted by @mrkwnzl in https://github.com/mrkwnzl/cyphersystem-foundryvtt/pull/79#r599337299_

**Comment by NiceTSY** [comment]
Currently, I have only one idea for this:

- Using a singular and plural noun that can be modified inside the settings of the character sheets (like currencies).

**Comment by mrkwnzl** [comment]
The idea I had was to avoid using Power Shifts as a singular. To be honest, I’m not even sure right now, where we need it.

**Comment by mrkwnzl** [comment]
For now, I circumvented the need for translated power shifts, as those were used only in one macro, where I use the general term instead of the self-chosen term. Closing this for now, unless someone is really upset about this.
