### ISSUE TITLE
Italian Translation

### ISSUE THREAD

**Issue by Eligor** [mrkwnzl/cyphersystem-foundryvtt#89]

**Comment by mrkwnzl** [comment]
@Eligor Everything is set up now. You can work on the translation here: [https://trans.etranslator.eu/projects/foundry-cypher-system/system/it/]()

The “Translate” button should send you to the translation interface where you can go through the strings one by one.

Thank you so much for working on that! Let me know if you have questions.

**Comment by mrkwnzl** [comment]
Quick heads up: I added Actor and Item strings to the English source file, so that the terms are translated as well. Those need translations as well.

**Comment by mrkwnzl** [comment]
I’m going to close this for now. This has only stayed open because it was never 100% translated into Italian, but the groundwork is done and it’s currently 90% translated. That has be be good enough.
