### ISSUE TITLE
Brazilian Portuguese Translation

### ISSUE THREAD

**Issue by AgostinhoMestre** [mrkwnzl/cyphersystem-foundryvtt#92]
Here I am
Let's translate to portuguese pt_BR

Where do we start?

**Comment by mrkwnzl** [comment]
A translation tool is now set up. You can work on the translation here: [https://trans.etranslator.eu/projects/foundry-cypher-system/system/pt_BR/]()

The “Translate” button should send you to the translation interface where you can go through the strings one by one.

Thank you so much for working on that! Let me know if you have questions.

**Comment by AgostinhoMestre** [comment]
After translating the entry, I must click on which button to end, since the "save" button is blocked?

**Comment by mrkwnzl** [comment]
I think you need an account in order to save directly. Without an account, you can only make a suggestion.

**Comment by AgostinhoMestre** [comment]
Weird....i'm logged in.

**Comment by AgostinhoMestre** [comment]
Oh....an account in the translator...ok.

**Comment by mrkwnzl** [comment]
Yeah, sorry, should have been more clear. If you don’t want to create an account, suggestions are fine as well.

**Comment by mrkwnzl** [comment]
Quick heads up: I added Actor and Item strings to the English source file, so that the terms are translated as well. Those need translations as well.
